/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the bill_details table.
 */
public class BillDetailsPk implements Serializable
{
	protected int billId;

	protected int userId;

	/** 
	 * This attribute represents whether the primitive attribute billId is null.
	 */
	protected boolean billIdNull;

	/** 
	 * This attribute represents whether the primitive attribute userId is null.
	 */
	protected boolean userIdNull;

	/** 
	 * Sets the value of billId
	 */
	public void setBillId(int billId)
	{
		this.billId = billId;
	}

	/** 
	 * Gets the value of billId
	 */
	public int getBillId()
	{
		return billId;
	}

	/** 
	 * Sets the value of userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	/** 
	 * Gets the value of userId
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'BillDetailsPk'
	 * 
	 */
	public BillDetailsPk()
	{
	}

	/**
	 * Method 'BillDetailsPk'
	 * 
	 * @param billId
	 * @param userId
	 */
	public BillDetailsPk(final int billId, final int userId)
	{
		this.billId = billId;
		this.userId = userId;
	}

	/** 
	 * Sets the value of billIdNull
	 */
	public void setBillIdNull(boolean billIdNull)
	{
		this.billIdNull = billIdNull;
	}

	/** 
	 * Gets the value of billIdNull
	 */
	public boolean isBillIdNull()
	{
		return billIdNull;
	}

	/** 
	 * Sets the value of userIdNull
	 */
	public void setUserIdNull(boolean userIdNull)
	{
		this.userIdNull = userIdNull;
	}

	/** 
	 * Gets the value of userIdNull
	 */
	public boolean isUserIdNull()
	{
		return userIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BillDetailsPk)) {
			return false;
		}
		
		final BillDetailsPk _cast = (BillDetailsPk) _other;
		if (billId != _cast.billId) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (billIdNull != _cast.billIdNull) {
			return false;
		}
		
		if (userIdNull != _cast.userIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + billId;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (billIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (userIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.BillDetailsPk: " );
		ret.append( "billId=" + billId );
		ret.append( ", userId=" + userId );
		return ret.toString();
	}

}
