/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class BugReportUser implements Serializable
{
	/** 
	 * This attribute maps to the column id in the bug_report_user table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column reported_by in the bug_report_user table.
	 */
	protected int reportedBy;

	/** 
	 * This attribute represents whether the attribute reportedBy has been modified since being read from the database.
	 */
	protected boolean reportedByModified = false;

	/** 
	 * This attribute maps to the column title in the bug_report_user table.
	 */
	protected String title;

	/** 
	 * This attribute represents whether the attribute title has been modified since being read from the database.
	 */
	protected boolean titleModified = false;

	/** 
	 * This attribute maps to the column bug in the bug_report_user table.
	 */
	protected String bug;

	/** 
	 * This attribute represents whether the attribute bug has been modified since being read from the database.
	 */
	protected boolean bugModified = false;

	/**
	 * Method 'BugReportUser'
	 * 
	 */
	public BugReportUser()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getReportedBy'
	 * 
	 * @return int
	 */
	public int getReportedBy()
	{
		return reportedBy;
	}

	/**
	 * Method 'setReportedBy'
	 * 
	 * @param reportedBy
	 */
	public void setReportedBy(int reportedBy)
	{
		this.reportedBy = reportedBy;
		this.reportedByModified = true;
	}

	/** 
	 * Sets the value of reportedByModified
	 */
	public void setReportedByModified(boolean reportedByModified)
	{
		this.reportedByModified = reportedByModified;
	}

	/** 
	 * Gets the value of reportedByModified
	 */
	public boolean isReportedByModified()
	{
		return reportedByModified;
	}

	/**
	 * Method 'getTitle'
	 * 
	 * @return String
	 */
	public String getTitle()
	{
		return title;
	}

	/**
	 * Method 'setTitle'
	 * 
	 * @param title
	 */
	public void setTitle(String title)
	{
		this.title = title;
		this.titleModified = true;
	}

	/** 
	 * Sets the value of titleModified
	 */
	public void setTitleModified(boolean titleModified)
	{
		this.titleModified = titleModified;
	}

	/** 
	 * Gets the value of titleModified
	 */
	public boolean isTitleModified()
	{
		return titleModified;
	}

	/**
	 * Method 'getBug'
	 * 
	 * @return String
	 */
	public String getBug()
	{
		return bug;
	}

	/**
	 * Method 'setBug'
	 * 
	 * @param bug
	 */
	public void setBug(String bug)
	{
		this.bug = bug;
		this.bugModified = true;
	}

	/** 
	 * Sets the value of bugModified
	 */
	public void setBugModified(boolean bugModified)
	{
		this.bugModified = bugModified;
	}

	/** 
	 * Gets the value of bugModified
	 */
	public boolean isBugModified()
	{
		return bugModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BugReportUser)) {
			return false;
		}
		
		final BugReportUser _cast = (BugReportUser) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (reportedBy != _cast.reportedBy) {
			return false;
		}
		
		if (reportedByModified != _cast.reportedByModified) {
			return false;
		}
		
		if (title == null ? _cast.title != title : !title.equals( _cast.title )) {
			return false;
		}
		
		if (titleModified != _cast.titleModified) {
			return false;
		}
		
		if (bug == null ? _cast.bug != bug : !bug.equals( _cast.bug )) {
			return false;
		}
		
		if (bugModified != _cast.bugModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + reportedBy;
		_hashCode = 29 * _hashCode + (reportedByModified ? 1 : 0);
		if (title != null) {
			_hashCode = 29 * _hashCode + title.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (titleModified ? 1 : 0);
		if (bug != null) {
			_hashCode = 29 * _hashCode + bug.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (bugModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return BugReportUserPk
	 */
	public BugReportUserPk createPk()
	{
		return new BugReportUserPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.BugReportUser: " );
		ret.append( "id=" + id );
		ret.append( ", reportedBy=" + reportedBy );
		ret.append( ", title=" + title );
		ret.append( ", bug=" + bug );
		return ret.toString();
	}

}
