/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Friends implements Serializable
{
	/** 
	 * This attribute maps to the column user_id in the friends table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the attribute userId has been modified since being read from the database.
	 */
	protected boolean userIdModified = false;

	/** 
	 * This attribute maps to the column friends_with in the friends table.
	 */
	protected int friendsWith;

	/** 
	 * This attribute represents whether the attribute friendsWith has been modified since being read from the database.
	 */
	protected boolean friendsWithModified = false;

	/**
	 * Method 'Friends'
	 * 
	 */
	public Friends()
	{
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdModified = true;
	}

	/** 
	 * Sets the value of userIdModified
	 */
	public void setUserIdModified(boolean userIdModified)
	{
		this.userIdModified = userIdModified;
	}

	/** 
	 * Gets the value of userIdModified
	 */
	public boolean isUserIdModified()
	{
		return userIdModified;
	}

	/**
	 * Method 'getFriendsWith'
	 * 
	 * @return int
	 */
	public int getFriendsWith()
	{
		return friendsWith;
	}

	/**
	 * Method 'setFriendsWith'
	 * 
	 * @param friendsWith
	 */
	public void setFriendsWith(int friendsWith)
	{
		this.friendsWith = friendsWith;
		this.friendsWithModified = true;
	}

	/** 
	 * Sets the value of friendsWithModified
	 */
	public void setFriendsWithModified(boolean friendsWithModified)
	{
		this.friendsWithModified = friendsWithModified;
	}

	/** 
	 * Gets the value of friendsWithModified
	 */
	public boolean isFriendsWithModified()
	{
		return friendsWithModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Friends)) {
			return false;
		}
		
		final Friends _cast = (Friends) _other;
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdModified != _cast.userIdModified) {
			return false;
		}
		
		if (friendsWith != _cast.friendsWith) {
			return false;
		}
		
		if (friendsWithModified != _cast.friendsWithModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + friendsWith;
		_hashCode = 29 * _hashCode + (friendsWithModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FriendsPk
	 */
	public FriendsPk createPk()
	{
		return new FriendsPk(userId, friendsWith);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.Friends: " );
		ret.append( "userId=" + userId );
		ret.append( ", friendsWith=" + friendsWith );
		return ret.toString();
	}

}
