/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the friends table.
 */
public class FriendsPk implements Serializable
{
	protected int userId;

	protected int friendsWith;

	/** 
	 * This attribute represents whether the primitive attribute userId is null.
	 */
	protected boolean userIdNull;

	/** 
	 * This attribute represents whether the primitive attribute friendsWith is null.
	 */
	protected boolean friendsWithNull;

	/** 
	 * Sets the value of userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	/** 
	 * Gets the value of userId
	 */
	public int getUserId()
	{
		return userId;
	}

	/** 
	 * Sets the value of friendsWith
	 */
	public void setFriendsWith(int friendsWith)
	{
		this.friendsWith = friendsWith;
	}

	/** 
	 * Gets the value of friendsWith
	 */
	public int getFriendsWith()
	{
		return friendsWith;
	}

	/**
	 * Method 'FriendsPk'
	 * 
	 */
	public FriendsPk()
	{
	}

	/**
	 * Method 'FriendsPk'
	 * 
	 * @param userId
	 * @param friendsWith
	 */
	public FriendsPk(final int userId, final int friendsWith)
	{
		this.userId = userId;
		this.friendsWith = friendsWith;
	}

	/** 
	 * Sets the value of userIdNull
	 */
	public void setUserIdNull(boolean userIdNull)
	{
		this.userIdNull = userIdNull;
	}

	/** 
	 * Gets the value of userIdNull
	 */
	public boolean isUserIdNull()
	{
		return userIdNull;
	}

	/** 
	 * Sets the value of friendsWithNull
	 */
	public void setFriendsWithNull(boolean friendsWithNull)
	{
		this.friendsWithNull = friendsWithNull;
	}

	/** 
	 * Gets the value of friendsWithNull
	 */
	public boolean isFriendsWithNull()
	{
		return friendsWithNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof FriendsPk)) {
			return false;
		}
		
		final FriendsPk _cast = (FriendsPk) _other;
		if (userId != _cast.userId) {
			return false;
		}
		
		if (friendsWith != _cast.friendsWith) {
			return false;
		}
		
		if (userIdNull != _cast.userIdNull) {
			return false;
		}
		
		if (friendsWithNull != _cast.friendsWithNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + friendsWith;
		_hashCode = 29 * _hashCode + (userIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (friendsWithNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.FriendsPk: " );
		ret.append( "userId=" + userId );
		ret.append( ", friendsWith=" + friendsWith );
		return ret.toString();
	}

}
