/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class GroupMembers implements Serializable
{
	/** 
	 * This attribute maps to the column group_id in the group_members table.
	 */
	protected int groupId;

	/** 
	 * This attribute represents whether the attribute groupId has been modified since being read from the database.
	 */
	protected boolean groupIdModified = false;

	/** 
	 * This attribute maps to the column user_id in the group_members table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the attribute userId has been modified since being read from the database.
	 */
	protected boolean userIdModified = false;

	/**
	 * Method 'GroupMembers'
	 * 
	 */
	public GroupMembers()
	{
	}

	/**
	 * Method 'getGroupId'
	 * 
	 * @return int
	 */
	public int getGroupId()
	{
		return groupId;
	}

	/**
	 * Method 'setGroupId'
	 * 
	 * @param groupId
	 */
	public void setGroupId(int groupId)
	{
		this.groupId = groupId;
		this.groupIdModified = true;
	}

	/** 
	 * Sets the value of groupIdModified
	 */
	public void setGroupIdModified(boolean groupIdModified)
	{
		this.groupIdModified = groupIdModified;
	}

	/** 
	 * Gets the value of groupIdModified
	 */
	public boolean isGroupIdModified()
	{
		return groupIdModified;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdModified = true;
	}

	/** 
	 * Sets the value of userIdModified
	 */
	public void setUserIdModified(boolean userIdModified)
	{
		this.userIdModified = userIdModified;
	}

	/** 
	 * Gets the value of userIdModified
	 */
	public boolean isUserIdModified()
	{
		return userIdModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GroupMembers)) {
			return false;
		}
		
		final GroupMembers _cast = (GroupMembers) _other;
		if (groupId != _cast.groupId) {
			return false;
		}
		
		if (groupIdModified != _cast.groupIdModified) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdModified != _cast.userIdModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + groupId;
		_hashCode = 29 * _hashCode + (groupIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return GroupMembersPk
	 */
	public GroupMembersPk createPk()
	{
		return new GroupMembersPk(groupId, userId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.GroupMembers: " );
		ret.append( "groupId=" + groupId );
		ret.append( ", userId=" + userId );
		return ret.toString();
	}

}
