/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the group_members table.
 */
public class GroupMembersPk implements Serializable
{
	protected int groupId;

	protected int userId;

	/** 
	 * This attribute represents whether the primitive attribute groupId is null.
	 */
	protected boolean groupIdNull;

	/** 
	 * This attribute represents whether the primitive attribute userId is null.
	 */
	protected boolean userIdNull;

	/** 
	 * Sets the value of groupId
	 */
	public void setGroupId(int groupId)
	{
		this.groupId = groupId;
	}

	/** 
	 * Gets the value of groupId
	 */
	public int getGroupId()
	{
		return groupId;
	}

	/** 
	 * Sets the value of userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	/** 
	 * Gets the value of userId
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'GroupMembersPk'
	 * 
	 */
	public GroupMembersPk()
	{
	}

	/**
	 * Method 'GroupMembersPk'
	 * 
	 * @param groupId
	 * @param userId
	 */
	public GroupMembersPk(final int groupId, final int userId)
	{
		this.groupId = groupId;
		this.userId = userId;
	}

	/** 
	 * Sets the value of groupIdNull
	 */
	public void setGroupIdNull(boolean groupIdNull)
	{
		this.groupIdNull = groupIdNull;
	}

	/** 
	 * Gets the value of groupIdNull
	 */
	public boolean isGroupIdNull()
	{
		return groupIdNull;
	}

	/** 
	 * Sets the value of userIdNull
	 */
	public void setUserIdNull(boolean userIdNull)
	{
		this.userIdNull = userIdNull;
	}

	/** 
	 * Gets the value of userIdNull
	 */
	public boolean isUserIdNull()
	{
		return userIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GroupMembersPk)) {
			return false;
		}
		
		final GroupMembersPk _cast = (GroupMembersPk) _other;
		if (groupId != _cast.groupId) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (groupIdNull != _cast.groupIdNull) {
			return false;
		}
		
		if (userIdNull != _cast.userIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + groupId;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (groupIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (userIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.GroupMembersPk: " );
		ret.append( "groupId=" + groupId );
		ret.append( ", userId=" + userId );
		return ret.toString();
	}

}
