/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class PasswordReset implements Serializable
{
	/** 
	 * This attribute maps to the column id in the password_reset table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column user_id in the password_reset table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the attribute userId has been modified since being read from the database.
	 */
	protected boolean userIdModified = false;

	/** 
	 * This attribute maps to the column reset_hash in the password_reset table.
	 */
	protected String resetHash;

	/** 
	 * This attribute represents whether the attribute resetHash has been modified since being read from the database.
	 */
	protected boolean resetHashModified = false;

	/**
	 * Method 'PasswordReset'
	 * 
	 */
	public PasswordReset()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdModified = true;
	}

	/** 
	 * Sets the value of userIdModified
	 */
	public void setUserIdModified(boolean userIdModified)
	{
		this.userIdModified = userIdModified;
	}

	/** 
	 * Gets the value of userIdModified
	 */
	public boolean isUserIdModified()
	{
		return userIdModified;
	}

	/**
	 * Method 'getResetHash'
	 * 
	 * @return String
	 */
	public String getResetHash()
	{
		return resetHash;
	}

	/**
	 * Method 'setResetHash'
	 * 
	 * @param resetHash
	 */
	public void setResetHash(String resetHash)
	{
		this.resetHash = resetHash;
		this.resetHashModified = true;
	}

	/** 
	 * Sets the value of resetHashModified
	 */
	public void setResetHashModified(boolean resetHashModified)
	{
		this.resetHashModified = resetHashModified;
	}

	/** 
	 * Gets the value of resetHashModified
	 */
	public boolean isResetHashModified()
	{
		return resetHashModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PasswordReset)) {
			return false;
		}
		
		final PasswordReset _cast = (PasswordReset) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdModified != _cast.userIdModified) {
			return false;
		}
		
		if (resetHash == null ? _cast.resetHash != resetHash : !resetHash.equals( _cast.resetHash )) {
			return false;
		}
		
		if (resetHashModified != _cast.resetHashModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdModified ? 1 : 0);
		if (resetHash != null) {
			_hashCode = 29 * _hashCode + resetHash.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (resetHashModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PasswordResetPk
	 */
	public PasswordResetPk createPk()
	{
		return new PasswordResetPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.PasswordReset: " );
		ret.append( "id=" + id );
		ret.append( ", userId=" + userId );
		ret.append( ", resetHash=" + resetHash );
		return ret.toString();
	}

}
