/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class User implements Serializable
{
	/** 
	 * This attribute maps to the column id in the user table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column email in the user table.
	 */
	protected String email;

	/** 
	 * This attribute represents whether the attribute email has been modified since being read from the database.
	 */
	protected boolean emailModified = false;

	/** 
	 * This attribute maps to the column salt in the user table.
	 */
	protected String salt;

	/** 
	 * This attribute represents whether the attribute salt has been modified since being read from the database.
	 */
	protected boolean saltModified = false;

	/** 
	 * This attribute maps to the column password in the user table.
	 */
	protected String password;

	/** 
	 * This attribute represents whether the attribute password has been modified since being read from the database.
	 */
	protected boolean passwordModified = false;

	/** 
	 * This attribute maps to the column active in the user table.
	 */
	protected short active;

	/** 
	 * This attribute represents whether the attribute active has been modified since being read from the database.
	 */
	protected boolean activeModified = false;

	/**
	 * Method 'User'
	 * 
	 */
	public User()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
		this.emailModified = true;
	}

	/** 
	 * Sets the value of emailModified
	 */
	public void setEmailModified(boolean emailModified)
	{
		this.emailModified = emailModified;
	}

	/** 
	 * Gets the value of emailModified
	 */
	public boolean isEmailModified()
	{
		return emailModified;
	}

	/**
	 * Method 'getSalt'
	 * 
	 * @return String
	 */
	public String getSalt()
	{
		return salt;
	}

	/**
	 * Method 'setSalt'
	 * 
	 * @param salt
	 */
	public void setSalt(String salt)
	{
		this.salt = salt;
		this.saltModified = true;
	}

	/** 
	 * Sets the value of saltModified
	 */
	public void setSaltModified(boolean saltModified)
	{
		this.saltModified = saltModified;
	}

	/** 
	 * Gets the value of saltModified
	 */
	public boolean isSaltModified()
	{
		return saltModified;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
		this.passwordModified = true;
	}

	/** 
	 * Sets the value of passwordModified
	 */
	public void setPasswordModified(boolean passwordModified)
	{
		this.passwordModified = passwordModified;
	}

	/** 
	 * Gets the value of passwordModified
	 */
	public boolean isPasswordModified()
	{
		return passwordModified;
	}

	/**
	 * Method 'getActive'
	 * 
	 * @return short
	 */
	public short getActive()
	{
		return active;
	}

	/**
	 * Method 'setActive'
	 * 
	 * @param active
	 */
	public void setActive(short active)
	{
		this.active = active;
		this.activeModified = true;
	}

	/** 
	 * Sets the value of activeModified
	 */
	public void setActiveModified(boolean activeModified)
	{
		this.activeModified = activeModified;
	}

	/** 
	 * Gets the value of activeModified
	 */
	public boolean isActiveModified()
	{
		return activeModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof User)) {
			return false;
		}
		
		final User _cast = (User) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		if (emailModified != _cast.emailModified) {
			return false;
		}
		
		if (salt == null ? _cast.salt != salt : !salt.equals( _cast.salt )) {
			return false;
		}
		
		if (saltModified != _cast.saltModified) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (passwordModified != _cast.passwordModified) {
			return false;
		}
		
		if (active != _cast.active) {
			return false;
		}
		
		if (activeModified != _cast.activeModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (emailModified ? 1 : 0);
		if (salt != null) {
			_hashCode = 29 * _hashCode + salt.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (saltModified ? 1 : 0);
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (passwordModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) active;
		_hashCode = 29 * _hashCode + (activeModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UserPk
	 */
	public UserPk createPk()
	{
		return new UserPk(id, email);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.User: " );
		ret.append( "id=" + id );
		ret.append( ", email=" + email );
		ret.append( ", salt=" + salt );
		ret.append( ", password=" + password );
		ret.append( ", active=" + active );
		return ret.toString();
	}

}
