/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.db.dao.BugReportUserDao;
import com.mybillr.db.dto.BugReportUser;
import com.mybillr.db.exceptions.BugReportUserDaoException;
import com.mybillr.db.factory.BugReportUserDaoFactory;

public class BugReportUserDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByUser(0);
		// findWhereIdEquals(0);
		// findWhereReportedByEquals(0);
		// findWhereTitleEquals("");
		// findWhereBugEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			BugReportUserDao _dao = getBugReportUserDao();
			BugReportUser _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUser'
	 * 
	 * @param reportedBy
	 */
	public static void findByUser(int reportedBy)
	{
		try {
			BugReportUserDao _dao = getBugReportUserDao();
			BugReportUser _result[] = _dao.findByUser(reportedBy);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			BugReportUserDao _dao = getBugReportUserDao();
			BugReportUser _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereReportedByEquals'
	 * 
	 * @param reportedBy
	 */
	public static void findWhereReportedByEquals(int reportedBy)
	{
		try {
			BugReportUserDao _dao = getBugReportUserDao();
			BugReportUser _result[] = _dao.findWhereReportedByEquals(reportedBy);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTitleEquals'
	 * 
	 * @param title
	 */
	public static void findWhereTitleEquals(String title)
	{
		try {
			BugReportUserDao _dao = getBugReportUserDao();
			BugReportUser _result[] = _dao.findWhereTitleEquals(title);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereBugEquals'
	 * 
	 * @param bug
	 */
	public static void findWhereBugEquals(String bug)
	{
		try {
			BugReportUserDao _dao = getBugReportUserDao();
			BugReportUser _result[] = _dao.findWhereBugEquals(bug);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getBugReportUserDao'
	 * 
	 * @return BugReportUserDao
	 */
	public static BugReportUserDao getBugReportUserDao()
	{
		return BugReportUserDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(BugReportUser dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getReportedBy() );
		buf.append( ", " );
		buf.append( dto.getTitle() );
		buf.append( ", " );
		buf.append( dto.getBug() );
		System.out.println( buf.toString() );
	}

}
