/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.db.dao.EmailsSentDao;
import com.mybillr.db.dto.EmailsSent;
import com.mybillr.db.exceptions.EmailsSentDaoException;
import com.mybillr.db.factory.EmailsSentDaoFactory;

public class EmailsSentDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByUser(0);
		// findByUser2(0);
		// findWhereIdEquals(0);
		// findWhereSenderIdEquals(0);
		// findWhereReceiverIdEquals(0);
		// findWhereSubjectEquals("");
		// findWhereContentEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUser'
	 * 
	 * @param senderId
	 */
	public static void findByUser(int senderId)
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findByUser(senderId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUser2'
	 * 
	 * @param receiverId
	 */
	public static void findByUser2(int receiverId)
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findByUser2(receiverId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSenderIdEquals'
	 * 
	 * @param senderId
	 */
	public static void findWhereSenderIdEquals(int senderId)
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findWhereSenderIdEquals(senderId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereReceiverIdEquals'
	 * 
	 * @param receiverId
	 */
	public static void findWhereReceiverIdEquals(int receiverId)
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findWhereReceiverIdEquals(receiverId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSubjectEquals'
	 * 
	 * @param subject
	 */
	public static void findWhereSubjectEquals(String subject)
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findWhereSubjectEquals(subject);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereContentEquals'
	 * 
	 * @param content
	 */
	public static void findWhereContentEquals(String content)
	{
		try {
			EmailsSentDao _dao = getEmailsSentDao();
			EmailsSent _result[] = _dao.findWhereContentEquals(content);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getEmailsSentDao'
	 * 
	 * @return EmailsSentDao
	 */
	public static EmailsSentDao getEmailsSentDao()
	{
		return EmailsSentDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(EmailsSent dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getSenderId() );
		buf.append( ", " );
		buf.append( dto.getReceiverId() );
		buf.append( ", " );
		buf.append( dto.getSubject() );
		buf.append( ", " );
		buf.append( dto.getContent() );
		System.out.println( buf.toString() );
	}

}
